# Generated by Django 5.1.2 on 2024-10-09 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbappdj2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handmadeitem',
            name='customers',
        ),
        migrations.AlterField(
            model_name='handmadeitem',
            name='date_receipt',
            field=models.DateField(blank=True, verbose_name='Date of receipt'),
        ),
        migrations.AlterField(
            model_name='material',
            name='color',
            field=models.CharField(blank=True, max_length=255, verbose_name='Material color'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='dbappdj2.customer', verbose_name='Customer Profile'),
        ),
        migrations.AddField(
            model_name='handmadeitem',
            name='customers',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handmade_items', to='dbappdj2.customer', verbose_name='Customers'),
        ),
    ]
