# Generated by Django 5.1.2 on 2024-10-09 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbappdj2', '0002_remove_handmadeitem_customers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='is_bought',
            field=models.CharField(choices=[('bought', 'Bought'), ('not_bought', 'Not Bought')], default='not_bought', max_length=10, verbose_name='Item Bought Status'),
        ),
        migrations.RemoveField(
            model_name='handmadeitem',
            name='customers',
        ),
        migrations.AlterField(
            model_name='profile',
            name='customer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='dbappdj2.customer', verbose_name='Customer Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handmadeitem',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='handmade_items', to='dbappdj2.customer', verbose_name='Customers'),
        ),
    ]
